# Generated by Django 2.0 on 2018-08-22 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='content',
            new_name='blog_content',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='title',
            new_name='blog_title',
        ),
    ]
